import image1 from './assets/Images/p6.jpg'
import image2 from './assets/Images/p7.jpg'
import image3 from './assets/Images/p4.jpg'
import image4 from './assets/Images/p2.jpg'
import image5 from './assets/Images/p3.jpg'
import image6 from './assets/Images/p5.jpg'
import image7 from './assets/Images/p7.jpg'
import image8 from './assets/Images/p1.jpg'
import image9 from './assets/Images/p9.jpg'
export default [image1,image2,image3,image4,image5,image6,image7,image8,image9];
